import { OpenSheetMusicDisplay } from 'opensheetmusicdisplay';
import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';

// Elements
const dropZone = document.getElementById('drop-zone');
const fileInput = document.getElementById('file-input');
const uploadBtn = document.getElementById('upload-btn');
const previewSection = document.getElementById('preview-section');
const uploadSection = document.getElementById('drop-zone');
const backBtn = document.getElementById('back-btn');
const downloadPdfBtn = document.getElementById('download-pdf-btn');
const osmdContainer = document.getElementById('osmd-container');
const fileNameDisplay = document.getElementById('file-name-display');
const loader = document.getElementById('loader');

let osmd;

// Initialize OSMD
function initOSMD() {
  osmd = new OpenSheetMusicDisplay(osmdContainer, {
    autoResize: true,
    drawTitle: true,
    drawSubtitle: true,
    drawComposer: true,
    drawLyricist: true,
    drawCredits: true,
    drawMetronomeMarks: true,
    coloringEnabled: true,
    renderBackend: 'canvas', // Changed from svg to canvas for better html2canvas compatibility
  });
}

initOSMD();

// File Handling Logic
async function handleFile(file) {
  if (!file) return;

  fileNameDisplay.textContent = file.name;
  loader.classList.remove('hidden');

  const reader = new FileReader();
  reader.onload = async (e) => {
    try {
      const content = e.target.result;
      await osmd.load(content);

      // Re-render with specific choral layout rules if needed
      osmd.setOptions({
        drawingParameters: "compact",
        coloringEnabled: true,
        defaultColorMusic: "#000000",
      });

      osmd.render();

      // Show preview
      uploadSection.classList.add('hidden');
      previewSection.classList.remove('hidden');
    } catch (error) {
      console.error("Error loading MusicXML:", error);
      alert("Error al cargar el archivo MusicXML. Asegúrate de que sea un archivo válido.");
    } finally {
      loader.classList.add('hidden');
    }
  };
  reader.readAsText(file);
}

// Events
uploadBtn.onclick = () => fileInput.click();

fileInput.onchange = (e) => {
  const file = e.target.files[0];
  handleFile(file);
};

dropZone.onclick = (e) => {
  if (e.target !== uploadBtn) {
    fileInput.click();
  }
};

dropZone.ondragover = (e) => {
  e.preventDefault();
  dropZone.classList.add('dragover');
};

dropZone.ondragleave = () => {
  dropZone.classList.remove('dragover');
};

dropZone.ondrop = (e) => {
  e.preventDefault();
  dropZone.classList.remove('dragover');
  const file = e.dataTransfer.files[0];
  handleFile(file);
};

backBtn.onclick = () => {
  previewSection.classList.add('hidden');
  uploadSection.classList.remove('hidden');
  fileInput.value = '';
};

downloadPdfBtn.onclick = async () => {
  loader.classList.remove('hidden');
  try {
    // We use the canvas elements directly generated by OSMD in the container
    const canvases = osmdContainer.getElementsByTagName('canvas');

    if (canvases.length === 0) {
      throw new Error("No canvas found to export.");
    }

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'px',
      format: [canvases[0].width, canvases[0].height]
    });

    for (let i = 0; i < canvases.length; i++) {
      if (i > 0) pdf.addPage([canvases[i].width, canvases[i].height], 'portrait');
      const imgData = canvases[i].toDataURL('image/png');
      pdf.addImage(imgData, 'PNG', 0, 0, canvases[i].width, canvases[i].height);
    }

    pdf.save(`${fileNameDisplay.textContent || 'partitura'}.pdf`);

  } catch (error) {
    console.error("Error generating PDF:", error);
    alert("Hubo un error al generar el PDF.");
  } finally {
    loader.classList.add('hidden');
  }
};
